spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
  # Non-sensitive production database configuration (placeholders only)
  datasource:
    url: jdbc:postgresql://prod-db:5432/profile_prod_db
    # Sensitive credentials are in Vault

# Production-specific settings
app:
  profile-service:
    feature-flags:
      enable-notifications: true
    logging:
      level: WARN
  notification-service:
    url: http://notification-service:8083 