spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  # Non-sensitive development database configuration (placeholders only)
  datasource:
    url: jdbc:postgresql://localhost:5433/profile_db
    # Sensitive credentials are in Vault

# Development-specific settings
app:
  profile-service:
    feature-flags:
      enable-notifications: true
    logging:
      level: DEBUG
  notification-service:
    url: http://localhost:8083 